# Generated by Django 5.2.5 on 2025-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_adresse_code_postal_candidature_est_supprime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='description',
        ),
        migrations.AddField(
            model_name='competence',
            name='niveau',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='INTERMEDIAIRE', max_length=15, verbose_name='Niveau'),
        ),
    ]
