# Generated by Django 5.2.5 on 2025-08-29 09:42

import candidats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0003_remove_competence_description_competence_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='est_public',
        ),
        migrations.AddField(
            model_name='document',
            name='date_obtention',
            field=models.DateField(blank=True, help_text='Date à laquelle vous avez obtenu ce document', null=True, verbose_name="Date d'obtention"),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text="Décrivez le contenu et l'importance de ce document", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=candidats.models.document_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='langue',
            field=models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('DE', 'Allemand'), ('IT', 'Italien'), ('AUTRE', 'Autre')], default='FR', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules (ex: python, gestion, leadership)', max_length=255, verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='taille_fichier',
            field=models.PositiveIntegerField(editable=False, verbose_name='Taille du fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('CV', 'Curriculum Vitae'), ('LM', 'Lettre de Motivation'), ('DIPLOME', 'Diplôme/Certificat'), ('ATTESTATION', 'Attestation de travail'), ('FORMATION', 'Attestation de formation'), ('RECOMMANDATION', 'Lettre de recommandation'), ('PORTFOLIO', 'Portfolio/Projets'), ('COMPETENCE', 'Certificat de compétence'), ('STAGE', 'Attestation de stage'), ('BENEVOLAT', 'Attestation bénévolat'), ('AUTRE', 'Autre document')], max_length=20, verbose_name='Type de document'),
        ),
    ]
