# Generated by Django 5.2.5 on 2025-08-29 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0004_remove_document_est_public_document_date_obtention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'entretien"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='evaluation_entretien',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Évaluation de l'entretien (1-5)"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='feedback_recruteur',
            field=models.TextField(blank=True, verbose_name='Feedback du recruteur'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='type_entretien',
            field=models.CharField(blank=True, choices=[('TELEPHONIQUE', 'Téléphonique'), ('VIDEO', 'Vidéo'), ('PRESENTIEL', 'Présentiel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcandidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'entretien"),
        ),
        migrations.AddField(
            model_name='historicalcandidature',
            name='evaluation_entretien',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Évaluation de l'entretien (1-5)"),
        ),
        migrations.AddField(
            model_name='historicalcandidature',
            name='feedback_recruteur',
            field=models.TextField(blank=True, verbose_name='Feedback du recruteur'),
        ),
        migrations.AddField(
            model_name='historicalcandidature',
            name='type_entretien',
            field=models.CharField(blank=True, choices=[('TELEPHONIQUE', 'Téléphonique'), ('VIDEO', 'Vidéo'), ('PRESENTIEL', 'Présentiel')], max_length=20, null=True),
        ),
    ]
