# Generated by Django 5.2.5 on 2025-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0005_candidature_date_entretien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un type de pièce'), ('biometrique', 'Carte biométrique'), ('nina', 'Carte NINA'), ('fiche', 'Fiche individuelle'), ('passport', 'Passeport')], max_length=20, verbose_name="Type de pièce d'identité"),
        ),
    ]
