# Generated by Django 5.2.5 on 2025-08-29 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0006_profilcandidat_numero_piece_identite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='ligne1',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='date_debut_recherche',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='mobilite_geographique',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='rayon_mobilite',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='salaire_max',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='salaire_min',
        ),
        migrations.AddField(
            model_name='adresse',
            name='quartier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quartier '),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='date_delivrance_piece',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Profil Facebook'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Profil Instagram'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='lieu_delivrance_piece',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de délivrance'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='localite_souhaitee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localité souhaitée'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='mission_temporaire',
            field=models.BooleanField(default=False, verbose_name='Accepte les missions temporaires'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='pretention_salariale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prétention salariale annuelle (FCFA)'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez une situation'), ('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation familiale'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='telephone_second',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\s*(?:\\d[\\s\\-()]?){8,}$')], verbose_name='Téléphone secondaire'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(blank=True, default='Mali', max_length=100, null=True, verbose_name='Pays'),
        ),
    ]
