# Generated by Django 5.2.5 on 2025-08-30 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0007_remove_adresse_code_postal_remove_adresse_ligne1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceprofessionnelle',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceprofessionnelle',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='pays_obtention',
            field=models.CharField(default='Mali', max_length=100, verbose_name="Pays d'obtention"),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('CV', 'Curriculum Vitae'), ('DIPLOME', 'Diplôme/Certificat'), ('PIECE_IDENTITE', "Pièce d'identité"), ('ATTESTATION', 'Attestation '), ('RECOMMANDATION', 'Lettre de recommandation'), ('COMPETENCE', 'Certificat de compétence'), ('AUTRE', 'Autre document')], max_length=20, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='experienceprofessionnelle',
            name='pays',
            field=models.CharField(default='Mali', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un type de pièce'), ('biometrique', 'Carte Biométrique'), ('nina', 'Carte NINA'), ('fiche', 'Fiche Individuelle'), ('passport', 'Passeport')], max_length=20, verbose_name="Type de pièce d'identité"),
        ),
    ]
