# Generated by Django 5.2.5 on 2025-09-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0008_experienceprofessionnelle_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Profil supprimé'),
        ),
    ]
