# Generated by Django 5.2.5 on 2025-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0009_profilcandidat_est_supprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='candidats', to='candidats.competence', verbose_name='Compétences'),
        ),
    ]
