# Generated by Django 5.2.5 on 2025-09-01 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0010_profilcandidat_competences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AddField(
            model_name='document',
            name='est_verifie',
            field=models.BooleanField(default=False, verbose_name='Document vérifié'),
        ),
        migrations.AddField(
            model_name='document',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
    ]
