# Generated by Django 5.2.5 on 2025-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0011_document_date_verification_document_est_verifie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='langue',
            field=models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('AR', 'Arabe'), ('AUTRE', 'Autre')], default='FR', max_length=10, verbose_name='Langue'),
        ),
    ]
