# Generated by Django 5.2.5 on 2025-09-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0013_rename_questions_posées_entretien_questions_posees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='type_entretien_prevue',
            field=models.CharField(blank=True, choices=[('TELEPHONIQUE', 'Téléphonique'), ('VIDEO', 'Vidéo'), ('PRESENTIEL', 'Présentiel')], default='PRESENTIEL', max_length=20, null=True, verbose_name="Type d'entretien prévu"),
        ),
        migrations.AlterField(
            model_name='historicalcandidature',
            name='type_entretien_prevue',
            field=models.CharField(blank=True, choices=[('TELEPHONIQUE', 'Téléphonique'), ('VIDEO', 'Vidéo'), ('PRESENTIEL', 'Présentiel')], default='PRESENTIEL', max_length=20, null=True, verbose_name="Type d'entretien prévu"),
        ),
    ]
