# Generated by Django 5.2.5 on 2025-09-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0014_alter_candidature_type_entretien_prevue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('POSTULE', 'Postulé'), ('ENTRETIEN', 'Entretien'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('RETIRE', 'Retiré')], default='POSTULE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcandidature',
            name='statut',
            field=models.CharField(choices=[('POSTULE', 'Postulé'), ('ENTRETIEN', 'Entretien'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('RETIRE', 'Retiré')], default='POSTULE', max_length=20),
        ),
    ]
