# Generated by Django 5.2.5 on 2025-09-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='commentaire_rh',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='jour_prevu',
        ),
    ]
