# Generated by Django 5.2.5 on 2025-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_tache_commentaire_rh_remove_tache_jour_prevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='commentaire_rh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='duree_estimee',
            field=models.PositiveIntegerField(blank=True, help_text='Durée estimée en minutes', null=True, verbose_name='Durée estimée'),
        ),
    ]
