# Generated by Django 5.2.5 on 2025-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('rh', 'Ressources Humaines'), ('employe', 'Employé'), ('stagiaire', 'Stagiaire'), ('entreprise', 'Entreprise'), ('consultant', 'Consultant'), ('candidat', 'Candidat')], max_length=20),
        ),
    ]
