# Generated by Django 5.2.5 on 2025-09-04 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_employeeprofile_fiche_poste_and_more'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='last_evaluation',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='competences',
            field=models.TextField(blank=True, help_text='Listez vos compétences séparées par des virgules'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='fiche_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.ficheposte'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='telephone_perso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='telephone_pro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
