# Generated by Django 5.2.5 on 2025-09-04 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_employeeprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil Employé', 'verbose_name_plural': 'Profils Employés'},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='salary',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif dans le système'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='annees_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='axes_amelioration',
            field=models.TextField(blank=True, verbose_name="Axes d'amélioration"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bureau',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bureau/Poste de travail'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='code_employe',
            field=models.CharField(blank=True, help_text="Code unique d'identification", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='competences_soft',
            field=models.TextField(blank=True, verbose_name='Compétences comportementales'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cout_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire + charges + avantages', max_digits=12, null=True, verbose_name='Coût total mensuel'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_integration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'intégration"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='derniere_evaluation',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière évaluation'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Autres documents'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='domaine_etude',
            field=models.CharField(blank=True, max_length=100, verbose_name="Domaine d'étude"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email_pro',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='manager_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_geres', to=settings.AUTH_USER_MODEL, verbose_name='Manager RH attitré'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac2', 'Bac+2 (BTS, DUT)'), ('bac3', 'Bac+3 (Licence)'), ('bac5', 'Bac+5 (Master)'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='niveau_global',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('intermediaire', 'Intermédiaire'), ('senior', 'Sénior')], max_length=20, verbose_name='Niveau global'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notes_rh',
            field=models.TextField(blank=True, verbose_name='Notes RH internes'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='objectifs',
            field=models.TextField(blank=True, verbose_name='Objectifs individuels'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='points_forts',
            field=models.TextField(blank=True, verbose_name='Points forts'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='prochaine_evaluation',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine évaluation'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='productivite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Indice de productivité'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salaire_brut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire brut mensuel'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='satisfaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Niveau de satisfaction'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Site/Lieu de travail'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='taux_absenteeisme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Taux d'absentéisme (%)"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='temps_travail',
            field=models.CharField(blank=True, help_text='Ex: Temps plein, 80%, etc.', max_length=20, verbose_name='Temps de travail'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='competences',
            field=models.TextField(blank=True, help_text='Compétences séparées par des virgules', verbose_name='Compétences techniques'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact_urgence',
            field=models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence"),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Contrat de travail'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('interim', 'Intérim'), ('freelance', 'Freelance'), ('essai', "Période d'essai")], max_length=10, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département/Service'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Manager opérationnel'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes générales'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='porte',
            field=models.CharField(blank=True, max_length=50, verbose_name='Porte/N°'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='poste_occupe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste occupé'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='remote_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Jours de télétravail/semaine'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='rue',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('pause', 'En pause'), ('termine', 'Terminé'), ('candidat', 'Candidat')], default='candidat', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='telephone_perso',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone personnel'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='telephone_pro',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Ex: 9h-17h, Lundi-Vendredi', max_length=50, verbose_name='Horaires de travail'),
        ),
    ]
