# Generated by Django 5.2.5 on 2025-09-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='code_employe',
        ),
    ]
