# Generated by Django 5.2.5 on 2025-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_employeeprofile_derniere_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('interim', 'Intérim'), ('consultant', 'Consultant'), ('essai', "Période d'essai")], max_length=10, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('pause', 'En pause'), ('termine', 'Terminé')], default='candidat', max_length=10, verbose_name='Statut'),
        ),
    ]
