# Generated by Django 5.2.5 on 2025-08-20 21:52

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantQuickApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom*')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel*')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone*')),
                ('expertise', models.CharField(max_length=200, verbose_name="Domaine d'expertise*")),
                ('experience', models.CharField(choices=[('junior', '1-3 ans'), ('confirmed', '4-6 ans'), ('senior', '7-9 ans'), ('expert', '10+ ans')], max_length=10, verbose_name="Niveau d'expérience*")),
                ('cv', models.FileField(blank=True, null=True, upload_to='consultants/cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='CV (PDF uniquement)*')),
                ('personal_message', models.TextField(blank=True, help_text='Laissez-nous un message si vous souhaitez ajouter des informations', null=True, verbose_name='Message personnel (facultatif)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inscription rapide',
                'verbose_name_plural': 'Inscriptions rapides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'Demande générale'), ('expert', 'Demande expert')], max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=5000)),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('sector', models.CharField(blank=True, max_length=250, verbose_name='Secteur')),
                ('phone', models.CharField(blank=True, help_text='Format : +223 XX XXX XXX ou 00223XXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?[\\d\\s]{10,20}$')], verbose_name='Téléphone')),
                ('subject', models.CharField(blank=True, choices=[('info', "Demande d'information"), ('rdv', 'Prise de rendez-vous'), ('service', 'Demande de service'), ('autre', 'Autre demande')], max_length=250, verbose_name='Objet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom*')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel*')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('mobility', models.CharField(blank=True, choices=[('locale', 'Locale'), ('nationale', 'Nationale'), ('internationale', 'Internationale')], max_length=20, verbose_name='Mobilité')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nationalité')),
                ('expertise', models.TextField(verbose_name="Domaine principal d'expertise*")),
                ('intervention_domains', models.TextField(blank=True, help_text='Listez les types de missions sur lesquelles vous pourriez être affecté', verbose_name="Domaines d'intervention")),
                ('missions_data', models.JSONField(default=list, verbose_name='Expériences missions')),
                ('availability_status', models.CharField(blank=True, choices=[('immediate', 'Disponible immédiatement'), ('delayed', 'Disponible sous X jours')], max_length=20, verbose_name='Disponibilité')),
                ('availability_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jours avant disponibilité')),
                ('mission_type_preference', models.CharField(blank=True, choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('short_term', 'Courte durée'), ('long_term', 'Longue durée')], max_length=20, verbose_name='Type de mission préféré')),
                ('max_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée maximum (mois)')),
                ('cv', models.FileField(blank=True, upload_to='consultants/cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='CV')),
                ('linkedin', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn')),
                ('portfolio', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Portfolio')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('competencies', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Compétences techniques')),
            ],
            options={
                'verbose_name': 'Candidature Consultant',
                'verbose_name_plural': 'Candidatures Consultants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la mission')),
                ('experience', models.CharField(choices=[('junior', '1-3 ans'), ('confirmed', '4-6 ans'), ('senior', '7-9 ans'), ('expert', '10+ ans')], max_length=10, verbose_name='Expérience sur cette mission')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='site_web.consultantquickapplication')),
            ],
        ),
    ]
