# Generated by Django 5.2.5 on 2025-08-22 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantquickapplication',
            name='enrollment_type',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('candidate', 'Candidat')], default='candidate', max_length=20, verbose_name="Type d'enregistrement"),
        ),
        migrations.AddField(
            model_name='consultantquickapplication',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='consultantquickapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
