# Generated by Django 5.2.5 on 2025-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_consultantquickapplication_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantquickapplication',
            name='enrollment_type',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('candidate', 'Candidat')], default='candidate', max_length=50, verbose_name="Type d'enregistrement"),
        ),
    ]
