# Generated by Django 5.2.5 on 2025-08-20 21:52

import django.db.models.deletion
import django.utils.timezone
import django_summernote.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('type_offre', models.CharField(choices=[('emploi', "Offre d'emploi"), ('appel_offre', "Appel d'offres"), ('autre', 'Autre')], default='emploi', max_length=20)),
                ('societe', models.CharField(default='Antares', max_length=255)),
                ('nombre_candidat', models.PositiveIntegerField(default=1, verbose_name='Nombre de candidats')),
                ('mission_principale', models.TextField(blank=True)),
                ('taches', models.TextField(blank=True)),
                ('profil_recherche', models.TextField(blank=True)),
                ('competences_qualifications', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('comment_postuler', models.TextField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('salaire', models.CharField(blank=True, max_length=100)),
                ('niveau_etude', models.CharField(blank=True, max_length=300, verbose_name="Niveau d'étude requis")),
                ('experience_requise', models.CharField(blank=True, help_text="Ex: '3 ans minimum'", max_length=300, verbose_name='Expérience requise')),
                ('secteur', models.CharField(blank=True, max_length=255)),
                ('fichier_pdf', models.FileField(blank=True, upload_to='offres_pdfs/')),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('expire', 'Expiré'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('visible_sur_site', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='SummernoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
