# Generated by Django 5.2.5 on 2025-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='nombre_candidat',
            field=models.CharField(blank=True, default='1', null=True, verbose_name='Nombre de candidats'),
        ),
    ]
