# Generated by Django 5.2.5 on 2025-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_nombre_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='secteur',
            field=models.CharField(choices=[('agriculture', 'Agriculture & Agro-business'), ('mines', 'Mines & Industrie'), ('btp', 'BTP & Architecture'), ('energie', 'Énergie & Utilities'), ('production', 'Production & Manutention'), ('logistique', 'Logistique & Transport'), ('commerce', 'Commerce & Vente'), ('banque', 'Banque, Finance & Assurance'), ('telecom', 'Télécoms & Informatique'), ('sante', 'Santé & Social'), ('education', 'Éducation & Formation'), ('tourisme', 'Tourisme & Hôtellerie'), ('ong', 'ONG & Coopération internationale'), ('admin', 'Administration Publique'), ('juridique', 'Juridique & Conseil'), ('marketing', 'Marketing & Communication'), ('rh', 'RH & Recrutement'), ('autre', 'Autre secteur')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='type_offre',
            field=models.CharField(choices=[('emploi', "Offre d'emploi"), ('appel_offre', "Appel d'offres"), ('autre', 'Autre')], default='emploi', max_length=50),
        ),
    ]
