# Generated by Django 5.2.5 on 2025-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_joboffer_secteur_alter_joboffer_type_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='secteur',
            field=models.CharField(choices=[('agriculture', 'Agriculture & Agro-alimentaire'), ('mines', 'Mines & Industries'), ('btp', 'BTP & Construction'), ('energie', 'Énergie & Eau'), ('commerce', 'Commerce & Vente'), ('finance', 'Finance & Assurance'), ('telecom', 'Télécoms & Digital'), ('sante', 'Santé & Social'), ('education', 'Éducation & Formation'), ('tourisme', 'Tourisme & Hôtellerie'), ('transport', 'Transport & Logistique'), ('ong', 'ONG & Coopération'), ('administration', 'Administration'), ('services', 'Services divers'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='societe',
            field=models.CharField(default='Antares Sarl', max_length=255),
        ),
    ]
